accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from .api_view import *
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    # path('signup',views.signup ,name='signup'),
    # path('signin',views.signin ,name='signin'),
    path('login/',views.signup,name='login'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('password_reset/',views.password_reset ,name='password_reset'),
    path('password_change/<slug:slug>',views.password_change ,name='password_change'),
    path('password_reset_set/<uidb64>/<token>/',views.password_reset_set ,name='password_reset_set'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
    
    
    
    
    # api
    # path('user/list',UserViewSet.as_view({'get': 'list'}))c,
    path('api/register',RegisterUserAPIView.as_view()),
    path('api/login',LoginView.as_view(),name='loginn'),
    path('api/profile/<slug:slug>',ProfileAPi.as_view()),
    path('api/profile/<slug:slug>/editprofile',ProfileAPIUpdate.as_view()),
    path('api/password_reset', password_reset.as_view(), name='password_reset'),
    path('api/password_reset_set/<uidb64>/<token>/', password_reset_set.as_view(), name='password_reset_set'),
    
    
    # path('user/list',PropertyAPiList.as_view(),name='PropertyAPiList'),
    
    
    # path('remove_myresevation/<int:resevation_id>',views.remove_myresevation ,name='remove_myresevation'),
    # path('remove_mylisting/<int:property_id>',views.remove_mylisting ,name='remove_mylisting'),
]

blog/urls.py
from django.urls import path 
from .views import *
from . import views
app_name='blog'


urlpatterns = [
    path('',views.home,name='home'),
    path('<slug:slug>',views.blog_content,name='blog_content'),
    path('is-like/<slug:slug>',views.is_like,name='is_like'),
    path('is-likeee/<slug:slug>',views.is_like_blog,name='is_like_blog'),
    path('add-comment/<slug:slug>',views.add_comment,name='add_comment'),
    path('blog/<slug:slug>',views.blog_user,name='blog_user'),
    path('blog/follow/<slug:slug>',views.add_follow,name='add_follow'),
    path('blog/un-follow/<slug:slug>',views.un_follow,name='un_follow'),
    
    path('create/<slug:slug>/create-blog',Upload_post.as_view(),name='create_blog'),
    
    path('all/user',views.all_user,name='all_user'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('blog.urls',namespace='blog')),
    
    
    path('api-auth/', include('rest_framework.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from accounts.models import Profile
from django.utils.translation import gettext_lazy as _
from datetime import datetime
# Create your models here.
from django.utils.text import slugify

class blog(models.Model):
    user=models.ForeignKey(Profile,blank=True, null=True,on_delete=models.CASCADE)
    title=models.CharField(max_length=500)
    text=models.TextField(max_length=10000)
    img=models.ImageField(upload_to='blog/')
    catergryy=models.ManyToManyField('catergry',blank=True, null=True)
    
    views=models.IntegerField(default=0)

    likes=models.ManyToManyField(Profile,blank=True, null=True, related_name='liked_posts')
    count_likes=models.IntegerField(default=0)

    Created_At=models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    
    slug=models.SlugField(blank=True, null=True)
    def __str__(self):
        return self.title 

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        else:
            self.slug = self.slug
        super(blog, self).save(*args, **kwargs)


class catergry(models.Model):
    title=models.CharField(max_length=100)
    
    def __str__(self):
        return self.title 


class Comments(models.Model):
    user=models.ForeignKey(Profile,blank=True, null=True,on_delete=models.CASCADE)
    blog=models.ForeignKey(blog,blank=True, null=True,on_delete=models.CASCADE)
    comment=models.CharField(max_length=500)
    Created_At=models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    
    def __str__(self):
        return str(self.user)

blog/views.py
from django.shortcuts import render,redirect
from.models import *
# Create your views here.
from django.shortcuts import get_object_or_404
from django.contrib import messages




def home(request):
    blogs=blog.objects.all()
    return render(request,'blog/index.html',{'blogs':blogs})


def blog_content(request,slug):
    blog_contents=blog.objects.get(slug=slug)
    profile = blog_contents.user
    catergries=catergry.objects.all()
    commnets=Comments.objects.filter(blog=blog_contents)
    profile.total_view += 1
    profile.save()
    blog_contents.views += 1
    blog_contents.save()
    return render(request,'blog/blog-content.html',{'blog_contents':blog_contents,
                                                    'catergries':catergries,
                                                    'commnets':commnets,})
    

def is_like(request, slug):
    profile=get_object_or_404(Profile,user=request.user)
    blog_contents=blog.objects.get(slug=slug)
    profile = blog_contents.user
    if profile not in blog_contents.likes.all():
        blog_contents.likes.add(profile)
        blog_contents.count_likes += 1
        profile.total_likesr += 1
        profile.save()
        blog_contents.save()
    return redirect('/')
    
    
    
def add_comment(request,slug):
    profile=get_object_or_404(Profile,user=request.user)
    blog_contents=get_object_or_404(blog,slug=slug)
    if 'message' in request.POST:
        message = request.POST['message']
        comment=Comments.objects.create(
                                user=profile,
                                blog=blog_contents,
                                comment=message,
                                )
        comment.save()
        return redirect('/' + blog_contents.slug)
    
    
def blog_user(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    blogs=blog.objects.filter(user=profile)
    return render(request,'blog/blog-user.html',{'blogs':blogs,
                                                'profile':profile})
    
def is_like_blog(request, slug):
    profile=get_object_or_404(Profile,user=request.user)
    blog_contents=blog.objects.get(slug=slug)
    profile = blog_contents.user
    if profile not in blog_contents.likes.all():
        blog_contents.likes.add(profile)
        blog_contents.count_likes += 1
        profile.total_likesr += 1
        profile.save()
        blog_contents.save()
    return redirect('/blog/' + blog_contents.user.slug)



def add_follow(request, slug):
    profile=get_object_or_404(Profile,user=request.user)
    profile_to_follow=get_object_or_404(Profile,slug=slug)
    profile_to_follow.follower.add(profile.user)
    profile_to_follow.count_follower += 1
    profile_to_follow.save()
    return redirect('/blog/' + profile_to_follow.slug)


def un_follow(request, slug):
    profile=get_object_or_404(Profile,user=request.user)
    profile_to_follow=get_object_or_404(Profile,slug=slug)
    profile_to_follow.follower.remove(profile.user)
    profile_to_follow.count_follower -= 1
    profile_to_follow.save()
    return redirect('/blog/' + profile_to_follow.slug)


def all_user(request):
    if request.user.is_authenticated:
        profiles = Profile.objects.filter(blog__isnull=False).exclude(user=request.user).distinct()
    else:
        profiles = Profile.objects.all()
    return render(request,'blog/all-user.html',{'profiles':profiles,})



from django.views.generic import CreateView
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

class Upload_post(LoginRequiredMixin,CreateView):
    model=blog
    fields=['title','text','img','catergryy',]
    template_name='blog/upload_post.html'
    def form_valid(self, form):
        form.instance.user = self.request.user.profile
        return super(Upload_post,self).form_valid(form)
    def get_success_url(self):
        return reverse_lazy('blog:blog_user', kwargs={'slug': self.kwargs['slug']})

blog/templates/blog/all-user.html
{% extends 'base.html' %}
{% load static %}
{% block body %} 
    <div class="user">
        {% for profile in profiles %}
            <div class="main">
                <div class="img">
                    <a href="">
                        {% if profile.image %}
                            <a href="{% url 'blog:blog_user' profile.slug %}"><img src="{{profile.image.url}}" alt="#"></a>
                        {% else %}
                            <a href="{% url 'blog:blog_user' profile.slug %}"><img src="{% static 'img/user_no_image.png' %}" alt="#"></a>
                        {% endif %}
                    </a>
                </div>
                <div class="content">
                    <div class="all-text">
                        <h5 style="    font-size: 11px;" class="content-text"> @ {{profile.user.username}}</h5>
                        <h5 class="content-main"> <a href="{% url 'blog:blog_user' profile.slug %}" style="color: #eee;">{{profile.user.first_name}} {{profile.user.last_name}}</a></h5>
                        <div class="categry">
                            {% if profile.facebook %}
                                <a href="{{profile.facebook}}">
                                    <img src="{% static 'img/facebook.png' %}" alt="#">
                                </a>
                            {% endif %}
                            {% if profile.instgram %}
                                    
                                <a href="{{profile.instgram}}">
                                    <img src="{% static 'img/ig-instagram-icon.svg' %}" alt="#">
                                </a>
                            {% endif %}
                            {% if profile.whatsapp %}
                                <a href="{{profile.whatsapp}}">
                                    <img src="{% static 'img/wa-whatsapp-icon.svg' %}" alt="#">
                                </a>
                            {% endif %}
                            {% if profile.linkedin %}
                                <a href="{{profile.linkedin}}">
                                    <img src="{% static 'img/linkedin-app-icon.svg' %}" alt="#">
                                </a>
                            {% endif %}
                            {% if profile.twitter  %}
                                <a href="{{profile.twitter}}">
                                    <img src="{% static 'img/x-social-media-logo-icon.svg' %}" alt="#">
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    
                        <div class="other">
                            <h5 class="content-view"> Follower : {{profile.count_follower}}</h5>
                            <h5 class="content-view"> total view : {{profile.total_view}} </h5>
                            <h5 class="content-like"> total likes : {{profile.total_likesr}} </h5>
                            
                            {% if user.is_authenticated %}
                                {% if profile.user == request.user %}
                                    <a class="upload" href="#">Upload</a>
                                {% else %}
                                    {% if request.user  in profile.follower.all %}
                                        <a class="upload" href="{% url 'blog:un_follow' profile.slug %}">Un Follow</a>
                                    {% else %}
                                        <a class="upload" href="{% url 'blog:add_follow' profile.slug %}">Follow</a>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                            <a class="upload" href="{% url 'accounts:login' %}">Log IN</a>
                            {% endif %}
                        </div>
                    
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock body %}

blog/templates/blog/blog-content.html
{% extends 'base.html' %}
{% load static %}
{% block body %} 
    <div class="blog">
        <div class="imgg" style="margin: auto;">
            <img src="{{blog_contents.img.url}}" alt="#">
        </div>

    </div>
    <div class="blog-text">
        <div class="main">
            <div class="content">
                <div class="all-text">
                    <h5 class="content-main">{{blog_contents.title}}</h5>
                    <h5 class="content-text">{{blog_contents.text}}</h5>
                    <div class="categry">
                        {% for cat in blog_contents.catergryy.all %}
                                <h5 class="cat">{{cat.title}}</h5>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="content">
                <h5 href="#" style="color: #eee; font-size: 35px;" class="content-main cattt">Categories</h5>
                <div style="    display: grid;
                padding-left: 73px;" class="all-text">
                    {% for caterg in catergries %}
                    <a style="color: #eee;
                    font-size: 25px;" href="#" class="content-text"> {{caterg.title}}</a>
                    {% endfor %}
                    
                </div>
            </div>
        </div>
    </div>


    <div class="blog">
        <h5 class="content-mainn"> Comments</h5>
        {% for commnet in commnets %}
            <div class="user-comment">
                <div class="main" style="    width: 50%">
                    <div class="img">
                        <a href="">
                            
                            {% if commnet.user.user.profile.image %}
                                <img src="{{commnet.user.user.profile.image.url}}" alt="#">
                                
                            {% endif %}
                                
                        </a>
                    </div>
                    <div class="content">
                        <div class="all-text">
                            <h5 style="    font-size: 11px;margin-bottom: 8px;margin-right: 8px;" class="content-text"> @ {{commnet.user.user.username}}</h5>
                            <h5 class="content-main">{{commnet.user.user.first_name}} {{commnet.user.user.last_name}}</h5>
                            <p class="content-main"> {{commnet.comment}} </p>
                            <p class="content-main" style="text-align: end;">{{commnet.Created_At}}</p>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        
        <div class="user-comment" style="    padding-bottom: 100px;">
            <div class="main" style="    width: 30%;transform: translateX(-30%);    display: grid;">
                <h5 class="content-main"> Add Comment</h5>
                
                {% if user.is_authenticated  %}
                    <form method="POST" action="{% url 'blog:add_comment' blog_contents.slug %}">
                        {% csrf_token %}
                        <div class="content" style="    width: 100%;    padding-left: 0px;">
                            <textarea name="message" rows="8" cols="80"></textarea>
                        </div>
                        <div class="content" style="width: 161px;
                        color: #eee;
                        border: 2px solid var(--five-color);
                        padding: 10px;
                        text-align: center;
                        border-radius: 10px;
                        margin: 0 auto;
                        margin-top: 20px;">
                            <button type="submit" style="color: #eee; background: none;
                            border: none;
                            font-size: 30px;" >Submit</button>
                        </div>
                    </form>
                {% else %}
                    <h5>you must login to can add comment ? <a class="content-main" href="{% url 'accounts:login' %}" style="    color: #eee;
                        border: 1px solid var(--five-color);
                        padding: 4px;
                        border-radius: 10px;">Log IN</a></h5>
                {% endif %}
                    
            </div>
        </div>
    </div>
    {% endblock body %}

blog/templates/blog/blog-user.html
{% extends 'base.html' %}
{% load static %}
{% block body %} 
    <div class="user">
        <div class="main">
            <div class="img">
                <a href="">
                    {% if profile.image %}
                        <img src="{{profile.image.url}}" alt="#">
                    {% else %}
                        <img src="{% static 'img/user_no_image.png' %}" alt="#">
                    {% endif %}
                </a>
            </div>
            <div class="content">
                <div class="all-text">
                    <h5 style="    font-size: 11px;" class="content-text"> @ {{profile.user.username}}</h5>
                    <h5 class="content-main"> {{profile.user.first_name}} {{profile.user.last_name}}</h5>
                    <div class="categry">
                        {% if profile.facebook %}
                            <a href="{{profile.facebook}}">
                                <img src="{% static 'img/facebook.png' %}" alt="#">
                            </a>
                        {% endif %}
                        {% if profile.instgram %}
                                
                            <a href="{{profile.instgram}}">
                                <img src="{% static 'img/ig-instagram-icon.svg' %}" alt="#">
                            </a>
                        {% endif %}
                        {% if profile.whatsapp %}
                            <a href="{{profile.whatsapp}}">
                                <img src="{% static 'img/wa-whatsapp-icon.svg' %}" alt="#">
                            </a>
                        {% endif %}
                        {% if profile.linkedin %}
                            <a href="{{profile.linkedin}}">
                                <img src="{% static 'img/linkedin-app-icon.svg' %}" alt="#">
                            </a>
                        {% endif %}
                        {% if profile.twitter  %}
                            <a href="{{profile.twitter}}">
                                <img src="{% static 'img/x-social-media-logo-icon.svg' %}" alt="#">
                            </a>
            {% endif %}
                    </div>
                </div>
                <div class="other">
                    <h5 class="content-view"> Follower : {{profile.count_follower}}</h5>
                    <h5 class="content-view"> total view : {{profile.total_view}} </h5>
                    <h5 class="content-like"> total likes : {{profile.total_likesr}} </h5>
                    
                    {% if user.is_authenticated %}
                        {% if profile.user == request.user %}
                            <a class="upload" href="{% url 'blog:create_blog' profile.slug %}">Upload</a>
                        {% else %}
                            {% if request.user  in profile.follower.all %}
                                <a class="upload" href="{% url 'blog:un_follow' profile.slug %}">Un Follow</a>
                            {% else %}
                                <a class="upload" href="{% url 'blog:add_follow' profile.slug %}">Follow</a>
                            {% endif %}
                        {% endif %}
                    {% else %}
                    <a class="upload" href="{% url 'accounts:login' %}">Log IN</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="blog">
        {% for blog in blogs %}
            <div class="main">
                <div class="img">
                    <a href="{% url 'blog:blog_content' blog.slug %}">
                        <img src="{{blog.img.url}}" alt="#">
                    </a>
                </div>
                <div class="content">
                    <div class="all-text">
                        <h5 class="content-main"><a href="{% url 'blog:blog_content' blog.slug %}" style="color: #eee;">{{blog.title}}</a></h5>
                        <h5 class="content-text">{{blog.text|striptags|truncatewords:35}}</h5>
                        
                        <div class="categry">
                            {% for cat in blog.catergryy.all %}
                                <h5 class="cat">{{cat.title}}</h5>
                            {% endfor %}
                            <a href="{% url 'blog:blog_content' blog.slug %}" style="    color: #eee;
                            border: 1px solid var(--five-color);
                            padding: 10px;
                            display: block;
                            width: 40%;
                            border-radius: 10px;
                            height: 33px;
                            justify-content: center;
                            align-items: center;
                            margin-left: 30px;
                            display: flex;">View More ...</a>
                        </div>
                    </div>
                    <div class="other">
                        <h5 class="content-view"> {{blog.views}} view </h5>
                        <h5 class="content-like"> {{blog.count_likes}} likes </h5>
                        {% if user.is_authenticated %} 
                            <a class="content-add-like" href="{% url 'blog:is_like' blog.slug %}"><i style="    font-size: 40px;    color: #eee;" class="fa-regular fa-heart"></i></a>
                        {% else %}
                            <a class="content-add-like" style="color: #eee;" href="{% url 'accounts:login' %}">Log In to can add like</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock body %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %} 
    <div class="blog">
        {% for blog in blogs %}
            <div class="main">
                <div class="img">
                    <a href="{% url 'blog:blog_content' blog.slug %}">
                        <img src="{{blog.img.url}}" alt="#">
                    </a>
                </div>
                <div class="content">
                    <div class="all-text">
                        <h5 class="content-main"><a href="{% url 'blog:blog_content' blog.slug %}" style="color: #eee;">{{blog.title}}</a></h5>
                        <h5 class="content-text">{{blog.text|striptags|truncatewords:35}}</h5>
                        
                        <div class="categry">
                            {% for cat in blog.catergryy.all %}
                                <h5 class="cat">{{cat.title}}</h5>
                            {% endfor %}
                            <a href="{% url 'blog:blog_content' blog.slug %}" style="    color: #eee;
                            border: 1px solid var(--five-color);
                            padding: 10px;
                            display: block;
                            width: 40%;
                            border-radius: 10px;
                            height: 33px;
                            justify-content: center;
                            align-items: center;
                            margin-left: 30px;
                            display: flex;">View More ...</a>
                        </div>
                    </div>
                    <div class="other">
                        <h5 class="content-view"> {{blog.views}} view </h5>
                        <h5 class="content-like"> {{blog.count_likes}} likes </h5>
                        
                        {% if user.is_authenticated %} 
                            <a class="content-add-like" href="{% url 'blog:is_like' blog.slug %}"><i style="    font-size: 40px;    color: #eee;" class="fa-regular fa-heart"></i></a>
                        {% else %}
                            <a class="content-add-like" style="color: #eee;" href="{% url 'accounts:login' %}">Log In to can add like</a>
                        {% endif %}
                            
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>

{% endblock body %}

blog/templates/blog/upload_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %} 
    <div class="blog">
        <div class="main">
            <form method="POST" enctype="multipart/form-data" style="width: 100%;">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button class="btn btn-primary"  style="display: flex;
                    margin: 0 auto;
                    margin-bottom: 20px;margin-top: 40px;
                    font-size: 27px;" type="submit">Post</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

{% endblock body %}