accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from .api_view import *
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    # path('signup',views.signup ,name='signup'),
    # path('signin',views.signin ,name='signin'),
    path('login/',views.signup,name='login'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('password_reset/',views.password_reset ,name='password_reset'),
    path('password_change/<slug:slug>',views.password_change ,name='password_change'),
    path('password_reset_set/<uidb64>/<token>/',views.password_reset_set ,name='password_reset_set'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
    
    
    
    
    # api
    # path('user/list',UserViewSet.as_view({'get': 'list'}))c,
    path('api/register',RegisterUserAPIView.as_view()),
    path('api/login',LoginView.as_view(),name='loginn'),
    path('api/profile/<slug:slug>',ProfileAPi.as_view()),
    path('api/profile/<slug:slug>/editprofile',ProfileAPIUpdate.as_view()),
    path('api/password_reset', password_reset.as_view(), name='password_reset'),
    path('api/password_reset_set/<uidb64>/<token>/', password_reset_set.as_view(), name='password_reset_set'),
    
    
    # path('user/list',PropertyAPiList.as_view(),name='PropertyAPiList'),
    
    
    # path('remove_myresevation/<int:resevation_id>',views.remove_myresevation ,name='remove_myresevation'),
    # path('remove_mylisting/<int:property_id>',views.remove_mylisting ,name='remove_mylisting'),
]

blog/urls.py
from django.urls import path 
from .views import *
from . import views
app_name='blog'


urlpatterns = [
    path('',views.home,name='home'),
    path('<slug:slug>',views.blog_content,name='blog_content'),
    path('is-like/<slug:slug>',views.is_like,name='is_like'),
    path('is-likeee/<slug:slug>',views.is_like_blog,name='is_like_blog'),
    path('add-comment/<slug:slug>',views.add_comment,name='add_comment'),
    path('blog/<slug:slug>',views.blog_user,name='blog_user'),
    path('blog/follow/<slug:slug>',views.add_follow,name='add_follow'),
    path('blog/un-follow/<slug:slug>',views.un_follow,name='un_follow'),
    
    path('create/<slug:slug>/create-blog',Upload_post.as_view(),name='create_blog'),
    
    path('all/user',views.all_user,name='all_user'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('blog.urls',namespace='blog')),
    
    
    path('api-auth/', include('rest_framework.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django_countries.fields import CountryField
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser, Group, Permission



class Profile(models.Model):
    user=models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    phone=models.CharField(max_length=20,verbose_name=_("phone"))
    slug=models.SlugField(blank=True, null=True) 
    image=models.ImageField(upload_to='profile/',blank=True, null=True)
    country=models.CharField(max_length=200,  null=True, choices=CountryField().choices + [('', 'Select Country')])
    adress=models.CharField(max_length=100)
    Token=models.CharField(max_length=500,blank=True, null=True)
    join_date=models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    
    follower=models.ManyToManyField(User,related_name='follower_user',blank=True, null=True)
    count_follower=models.IntegerField(default=0)
    
    total_view =models.IntegerField(default=0)
    total_likesr=models.IntegerField(default=0)
    
    
    # scoial
    
    facebook=models.URLField(blank=True, null=True)
    instgram=models.URLField(blank=True, null=True)
    whatsapp=models.URLField(blank=True, null=True)
    linkedin=models.URLField(blank=True, null=True)
    twitter=models.URLField(blank=True, null=True)
    
    def save(self ,*args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return '%s' %(self.user)

    def get_absolute_url(self):
        return reverse("accounts:Profile_detail", kwargs={"slug": self.slug})

    def create_profile(sender ,*args, **kwargs):
        if kwargs['created']:
            user_profile=Profile.objects.create(user=kwargs['instance'])    
    post_save.connect(create_profile , sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email','password1','password2']



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'email','first_name','last_name']


# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['image' , 'country', 'adress']

accounts/views.py
from django.contrib import messages
from django.shortcuts import render ,redirect ,get_object_or_404

from.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login ,authenticate
from django.http import HttpResponse,HttpResponseForbidden
from django_countries import countries
from.tokens import accout_actvation_token
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes,force_str
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from project import settings
from django.urls import reverse_lazy
from django.contrib.auth import logout

def activate_account(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and accout_actvation_token.check_token(user, token):
        # activate the user's account
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated!')
        login(request, user)
        return redirect('/')
    else:
        messages.error(request, 'Invalid activation link.')
        return redirect('/')


def signup(request):
    if request.method == 'POST' and 'signup' in request.POST:
        first_name=None
        email=None
        password=None
        passwordconfigration=None
        if 'first_name' in request.POST : first_name=request.POST['first_name']
        else :messages.error(request,'Error in First Name !')
        
        if 'email' in request.POST : email=request.POST['email']
        else : messages.error(request,'Error in Email !')
        
        if 'password' in request.POST: password=request.POST['password']
        else : messages.error(request,'Error in password !')
        
        if 'passwordconfigration' in request.POST: passwordconfigration=request.POST['passwordconfigration']
        else : messages.error(request,'Error in Password Configration !')
        context={'first_name':first_name,
                'email':email,}
        if first_name and email and password and passwordconfigration:
            if User.objects.filter(email=email).exists():
                messages.error(request,'This Email Name is taken !')
                return render(request,'registration/login.html',context)
            else:
                if password != passwordconfigration:
                    messages.error(request,'The two password fields didn’t match.')
                    return render(request,'registration/login.html',context)
                else:
                    username = email.split("@")[0]
                    user = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    is_active=False,
                    email=email,
                    password=password
                    )
                    user.save()
                    mailsubject='activate your account'
                    uid = urlsafe_base64_encode(force_bytes(user.pk))
                    token = accout_actvation_token.make_token(user)
                    message=f"Hi {user.username},\n\nPlease click on the following link to activate your account:\n\n{get_current_site(request).domain}/accounts/activate_account/{uid}/{token}/\n\nThanks!\n"
                    email_from = settings.EMAIL_HOST_USER
                    recipient_list = [user.email,] 
                    emailmessage=send_mail(mailsubject,message,email_from,recipient_list)

                    if emailmessage:
                        messages.success(request,f'User has been registered successfully , go to {email} to activate your account ! ')
                        return redirect('/accounts/login')
                    else:
                        messages.error(request,f'filed to send email to  {email} ! ')
                        return redirect('/accounts/login')
        else:
            messages.error(request,'Please fill in all fields !')
            return render(request,'registration/login.html',context)
        
            
    elif request.method == 'POST' and 'login' in request.POST:
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Go to'+email+'to active your account !')
                return redirect('/accounts/login')
        else:
            messages.error(request, 'Invalid email or password')
            return redirect('/accounts/login')
    else:
        return render(request,'registration/login.html')
    
def log_out(request):
    logout(request)
    return redirect('/')

    
def password_reset(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        if email:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None

            if user:
                mailsubject = 'Change A Password'
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = accout_actvation_token.make_token(user)
                user_profile = Profile.objects.get(user=user)
                user_profile.Token = str(uid) + '/' + token
                user_profile.save()
                message = f"Hi {user.username},\n\nPlease click on the following link to Change your Password\n\n{get_current_site(request).domain}/accounts/password_reset_set/{uid}/{token}/\n\nThanks!\n"
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [user.email,] 
                emailmessage = send_mail(mailsubject, message, email_from, recipient_list)

                if emailmessage:
                    messages.success(request, f'message has been  successfully, go to {email} Change your Password!')
                    return redirect('/accounts/login')
                else:
                    messages.error(request, f'Failed to send email to {email}!')
                    return redirect('/accounts/password_reset')
            else:
                messages.error(request, f'User with email {email} not found!')
                return redirect('/accounts/password_reset')
        else:
            messages.error(request, 'Email not provided in the request!')
            return redirect('/accounts/password_reset')

    return render(request, 'registration/password_reset.html')
    

def password_reset_set(request, uidb64, token):
    key = str(uidb64) + '/' + token
    try:
        userw = Profile.objects.get(Token=key)
    except Profile.DoesNotExist:
        return HttpResponse("Invalid token ! try to send message to your mail again !!")
    if request.method == 'POST':
        password = request.POST['password']
        passwordconfigration = request.POST['passwordconfigration']
        user = User.objects.get(username=userw.user)
        if 'password' in request.POST: password=request.POST['password']
        else : messages.error(request,'Error in password !')
        
        if 'passwordconfigration' in request.POST: passwordconfigration=request.POST['passwordconfigration']
        else : messages.error(request,'Error in Password Configration !')
        if password and passwordconfigration:
            if password != passwordconfigration:
                
                messages.error(request,'The two password fields didn’t match.')
                return render(request,'registration/change_password.html')
            else:
                user = userw.user
                user.set_password(password)
                user.save()
                userw.Token = None
                userw.save()
                messages.success(request,'password reset successfully !')
                return redirect('/accounts/login')
        else:
            messages.error(request,'Please fill in all fields !')
            return render(request,'registration/change_password.html')
    return render(request, 'registration/change_password.html')

@login_required(login_url='/accounts/login/')
def password_change(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    if request.user.id == profile.user.id:
        if request.method == 'POST':
            password = request.POST['password']
            passwordconfigration = request.POST['passwordconfigration']
            if 'password' in request.POST: password=request.POST['password']
            else : messages.error(request,'Error in password !')
            
            if 'passwordconfigration' in request.POST: passwordconfigration=request.POST['passwordconfigration']
            else : messages.error(request,'Error in Password Configration !')
            if password and passwordconfigration:
                if password != passwordconfigration:
                    
                    messages.error(request,'The two password fields didn’t match.')
                    return render(request,'registration/change_password.html')
                else:
                    user = User.objects.get(username=profile.user)
                    user.set_password(password)
                    user.save()
                    messages.success(request,'password reset successfully !')
                    return redirect('/accounts/login')
            else:
                messages.error(request,'Please fill in all fields !')
                return render(request,'registration/change_password.html')
        return render(request, 'registration/change_password.html')
    else:

accounts/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">


    <title>update my profile - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body {
            margin-top: 20px;
            color: #9b9ca1;
        }

        .bg-secondary-soft {
            background-color: rgba(208, 212, 217, 0.1) !important;
        }

        .rounded {
            border-radius: 5px !important;
        }

        .py-5 {
            padding-top: 3rem !important;
            padding-bottom: 3rem !important;
        }

        .px-4 {
            padding-right: 1.5rem !important;
            padding-left: 1.5rem !important;
        }

        .file-upload .square {
            height: 250px;
            width: 250px;
            margin: auto;
            vertical-align: middle;
            border: 1px solid #e5dfe4;
            background-color: #fff;
            border-radius: 5px;
        }

        .text-secondary {
            --bs-text-opacity: 1;
            color: rgba(208, 212, 217, 0.5) !important;
        }

        .btn-success-soft {
            color: #28a745;
            background-color: rgba(40, 167, 69, 0.1);
        }

        .btn-danger-soft {
            color: #dc3545;
            background-color: rgba(220, 53, 69, 0.1);
        }

        .form-control {
            display: block;
            width: 100%;
            padding: 0.5rem 1rem;
            font-size: 0.9375rem;
            font-weight: 400;
            line-height: 1.6;
            color: #29292e;
            background-color: rgba(208, 212, 217, 0.1) !important;
            background-clip: padding-box;
            border: none;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
        }
    </style>
</head>

<body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css"
        integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="my-5">
                    <h3>My Profile</h3>
                    <hr>
                </div>

                <form class="file-upload">
                    <div class="row mb-5 gx-5">

                        <div class="col-xxl-8 mb-5 mb-xxl-0">
                            <div class="bg-secondary-soft px-4 py-5 rounded">
                                <div class="row g-3">
                                    <h4 class="mb-4 mt-0">Contact detail</h4>

                                    <div class="col-md-6">
                                        <label class="form-label">First Name *</label>
                                        <label type="text" class="form-control" value="Scaralet">{{profile.user.first_name}}</label>
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label">Last Name *</label>
                                        <label type="text" class="form-control" placeholder aria-label="Last name"
                                            value="Doe">{{profile.user.last_name}}</label>
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label">Phone number *</label>
                                        <label type="text" class="form-control" placeholder aria-label="Phone number"
                                            value="(333) 000 555">{{profile.phone}} </label>
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label">Country</label>
                                        <label type="text" class="form-control" placeholder aria-label="Phone number"
                                            value="+91 9852 8855 252">{{profile.country.name}}</label>
                                    </div>

                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">Email *</label>
                                        <label type="email" class="form-control" id="inputEmail4"
                                            value="example@homerealty.com">{{profile.user.email}}</label>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">Address *</label>
                                        <label type="email" class="form-control" id="inputEmail4"
                                            value="example@homerealty.com">{{profile.adress}}</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xxl-4">
                            <div class="bg-secondary-soft px-4 py-5 rounded">
                                <div class="row g-3">
                                    <h4 style="text-align: center;" class="mb-4 mt-0">Profile photo</h4>
                                    <div class="text-center">

                                        <div class="square position-relative display-2 mb-3" style="border: 2px solid #7f7a7a;display: flex;align-items: center;border-radius: 50%;">
                                            {% if profile.image  %}
                                                <img class="profile-img" style="width: 235px;height: 235px;border-radius: 50%;margin: 0 auto;" src="{{profile.image.url}}" alt="card-img-top">
                                            {% else %}
                                                <img class="profile-img-defult" style="width: 235px;height: 235px;border-radius: 50%;margin: 0 auto;" src="{% static 'user_no_image.png' %}" alt="card-img-top">
                                                
                                            {% endif %}
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-12 gx-12" style="justify-content: center;">
                        <div class="col-xxl-3 mb-5 mb-xxl-0 justify-content-md-end text-center">
                            <a href="{% url 'accounts:password_change' slug=user.profile.slug %}" type="button" class="btn btn-primary btn-lg">Chagne Password</a>
                        </div>
                        <div class="col-xxl-3 mb-5 mb-xxl-0 justify-content-md-end text-center">
                            <a href="{% url 'accounts:edit' slug=user.profile.slug%}" type="button" class="btn btn-primary btn-lg">Edit My Profile</a>
                        </div>

                    </div>
                    <!-- <div class="row mb-12 gx-12">
                        <div class="col-xxl-8 mb-5 mb-xxl-0">
                            <div class="bg-secondary-soft px-4 py-5 rounded">
                                <div class="row g-3">
                                    <h4 class="mb-4 mt-0">Social media detail</h4>

                                    <div class="col-md-6">
                                        <a class="form-label"><i
                                                class="fab fa-fw fa-facebook me-2 text-facebook"></i>Facebook *</a>
                                        <input type="text" class="form-control" placeholder aria-label="Facebook"
                                            value="http://www.facebook.com">
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label"><i
                                                class="fab fa-fw fa-twitter text-twitter me-2"></i>Twitter *</label>
                                        <input type="text" class="form-control" placeholder aria-label="Twitter"
                                            value="http://www.twitter.com">
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label"><i
                                                class="fab fa-fw fa-linkedin-in text-linkedin me-2"></i>Linkedin
                                            *</label>
                                        <input type="text" class="form-control" placeholder aria-label="Linkedin"
                                            value="http://www.linkedin.com">
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label"><i
                                                class="fab fa-fw fa-instagram text-instagram me-2"></i>Instagram
                                            *</label>
                                        <input type="text" class="form-control" placeholder aria-label="Instragram"
                                            value="http://www.instragram.com">
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label"><i
                                                class="fas fa-fw fa-basketball-ball text-dribbble me-2"></i>Dribble
                                            *</label>
                                        <input type="text" class="form-control" placeholder aria-label="Dribble"
                                            value="http://www.dribble.com">
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label"><i
                                                class="fab fa-fw fa-pinterest text-pinterest"></i>Pinterest *</label>
                                        <input type="text" class="form-control" placeholder aria-label="Pinterest"
                                            value="http://www.pinterest.com">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-3 mb-5 mb-xxl-0 justify-content-md-end text-center">
                            <button type="button" class="btn btn-primary btn-lg">Edit My Profile</button>
                        </div>

                    </div> -->

                    
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">

    </script>
</body>

</html>

accounts/templates/tempactvationaccount.html
{% autoescape off %}
    Hi {{ user.username }},
    Click <a href="{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}">here</a> to activate your account.
{% endautoescape %}