accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from .api_view import *
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    # path('signup',views.signup ,name='signup'),
    # path('signin',views.signin ,name='signin'),
    path('login/',views.signup,name='login'),
    path('activate_account/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('log_out',views.log_out ,name='log_out'),
    path('password_reset/',views.password_reset ,name='password_reset'),
    path('password_change/<slug:slug>',views.password_change ,name='password_change'),
    path('password_reset_set/<uidb64>/<token>/',views.password_reset_set ,name='password_reset_set'),
    path('profile/<slug:slug>',views.profile ,name='profile'),
    path('profile/<slug:slug>/editprofile',views.edit_profile ,name='edit'),
    
    
    
    
    # api
    # path('user/list',UserViewSet.as_view({'get': 'list'}))c,
    path('api/register',RegisterUserAPIView.as_view()),
    path('api/login',LoginView.as_view(),name='loginn'),
    path('api/profile/<slug:slug>',ProfileAPi.as_view()),
    path('api/profile/<slug:slug>/editprofile',ProfileAPIUpdate.as_view()),
    path('api/password_reset', password_reset.as_view(), name='password_reset'),
    path('api/password_reset_set/<uidb64>/<token>/', password_reset_set.as_view(), name='password_reset_set'),
    
    
    # path('user/list',PropertyAPiList.as_view(),name='PropertyAPiList'),
    
    
    # path('remove_myresevation/<int:resevation_id>',views.remove_myresevation ,name='remove_myresevation'),
    # path('remove_mylisting/<int:property_id>',views.remove_mylisting ,name='remove_mylisting'),
]

blog/urls.py
from django.urls import path 
from .views import *
from . import views
app_name='blog'


urlpatterns = [
    path('',views.home,name='home'),
    path('<slug:slug>',views.blog_content,name='blog_content'),
    path('is-like/<slug:slug>',views.is_like,name='is_like'),
    path('is-likeee/<slug:slug>',views.is_like_blog,name='is_like_blog'),
    path('add-comment/<slug:slug>',views.add_comment,name='add_comment'),
    path('blog/<slug:slug>',views.blog_user,name='blog_user'),
    path('blog/follow/<slug:slug>',views.add_follow,name='add_follow'),
    path('blog/un-follow/<slug:slug>',views.un_follow,name='un_follow'),
    
    path('create/<slug:slug>/create-blog',Upload_post.as_view(),name='create_blog'),
    
    path('all/user',views.all_user,name='all_user'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('blog.urls',namespace='blog')),
    
    
    path('api-auth/', include('rest_framework.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    </head>

    <body style="background-image: url({% static 'img/5192479.jpg' %});">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarTogglerDemo03"
                    aria-controls="navbarTogglerDemo03" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/">Moody Blog</a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:all_user' %}">All User</a>
                        </li>
                        <li class="nav-item">
                            
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'blog:blog_user' request.user.profile.slug %}">My Blog </a>
                            {% else %}
                                <a class="nav-link" href="{% url 'accounts:login' %}">Log In to Can Add Post</a>
                            {% endif %}
                                
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link disabled"
                                aria-disabled="true">User Name : {{request.user}}</a>
                            {% else %}
                            <a class="nav-link disabled"
                            aria-disabled="true">none user</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search"
                            placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success"
                            type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="categryy">
            
            {% if socials.facebook %}
                <a href="{{socials.facebook}}">
                    <img src="{% static 'img/facebook.png' %}" alt="#">
                </a>
            {% endif %}
            {% if socials.instgram %}
                    
                <a href="{{socials.instgram}}">
                    <img src="{% static 'img/ig-instagram-icon.svg' %}" alt="#">
                </a>
            {% endif %}
            {% if socials.whatsapp %}
                <a href="{{socials.whatsapp}}">
                    <img src="{% static 'img/wa-whatsapp-icon.svg' %}" alt="#">
                </a>
            {% endif %}
            {% if socials.linkedin %}
                <a href="{{socials.linkedin}}">
                    <img src="{% static 'img/linkedin-app-icon.svg' %}" alt="#">
                </a>
            {% endif %}
            {% if socials.twitter  %}
                <a href="{{socials.twitter}}">
                    <img src="{% static 'img/x-social-media-logo-icon.svg' %}" alt="#">
                </a>
            {% endif %}
        </div>
        
        {% block body %}
            
        {% endblock body %}

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>

</html>